### ISSUE TITLE
add support for building java21 code

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko#1033]
https://github.com/apache/incubator-pekko/pull/1023 added java 21 code to our docs. I don't believe that we have support for building this code to see if compiles. We have https://github.com/apache/incubator-pekko/blob/main/project/Jdk9.scala and can look into adding a Java 21 equivalent.

**Comment by He-Pin** [comment]
I can do that on weekend, I was planning to open issue like this.

And I think this is a good first issue too

**Comment by naosense** [comment]
@He-Pin hi, I want to take this, can you guide me on how to do it?

**Comment by He-Pin** [comment]
@naosense https://github.com/apache/incubator-pekko/pull/1072 & https://github.com/apache/incubator-pekko/pull/1054 Can you help check it really works, thanks.
