### ISSUE TITLE
EventStream documentation on Typed is required

### ISSUE THREAD

**Issue by Roiocam** [apache/pekko#1162]
Pekko has EventBus(low-level) and EventStream documentation on Classic: https://pekko.apache.org/docs/pekko/current/event-bus.html

But there is no documentation on typed at present.

**Comment by sfali** [comment]
I can pick this, couple of question, what is the timeline to finish this? Will it be straight from Akka documentation of typed EventBus?

**Comment by pjfanning** [comment]
@sfali please do not copy anything from Akka. You can't take copyrighted text from another web site due to the legal implications.

**Comment by sfali** [comment]
Getting compilation on `Unsafe` that `sun.misc.Unsafe` not found, how to get around this?

**Comment by pjfanning** [comment]
> Getting compilation on `Unsafe` that `sun.misc.Unsafe` not found, how to get around this?

What version of Java are you using? Java 11 is recommended for building Pekko.

**Comment by sfali** [comment]
I am using Java 17, let me switch to Java 11
