### ISSUE TITLE
SubFlow's don't correctly propagate `Supervision.resumeStrategy`

### ISSUE THREAD

**Issue by mdedetrich** [apache/pekko#1205]
In https://github.com/apache/incubator-pekko/pull/252 I made it so that we can set `SupervisionStrategy` rather than using `SubStreamCancelStrategy`. It turns out there is an existing test which was written as pending (so its currently disabled) to test this exact `SupervisionStrategy` functionality (specifically `SupervisionStrategy.resumingDecider` when an exception is thrown) when its adding in the future (which is now) i.e.

https://github.com/apache/incubator-pekko/blob/c44c0b7cbdab11d85176cfe062288fdcba16c56a/stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowSplitAfterSpec.scala#L213-L262

When I try to enable the test by removing `pending` so the test runs it actually does not pass which means that the `SupervisionStrategy.resumingDecider` is not properly catching and suppressing the exception as its meant to do so.

**Comment by mdedetrich** [comment]
So I set the 1.1.0-M1 milestone for this bug, will do my best to solve it by the time the release is actually cut however if its not done by then can do it in a following `-M2` or full release.

It does however need to be solved by full 1.1.0 release

**Comment by gwak** [comment]
Hi @mdedetrich,

@pjfanning and I just tested the 1.1 milestone release with **[playframework](https://github.com/playframework/playframework/pull/12662)**. We followed the migration guide and explicitly defined the supervision strategy when using the `splitWhen` function like so:

```scala
.splitWhen(_.isLeft)
.withAttributes(ActorAttributes.supervisionStrategy(Supervision.resumingDecider))
.prefixAndTail(1)
```

But when using the deprecated `SubstreamCancelStrategy` it works fine:

```scala
.splitWhen(SubstreamCancelStrategy.drain)(_.isLeft)
```

Is there something we're missing ?

**Comment by mdedetrich** [comment]
@gwak So I still need to work on this, in the meantime I would recommend using the deprecated method as you described.

I just skimmed through the issue to recover some context, iirc the core issue is that in general `ActorAttributes` are not propagating where as in Pekko 1.0 and/or current pekko 1.1 deprecation functionality propagates the strategy in a different/more explicit way

**Comment by mdedetrich** [comment]
Re-opening this as it needs to be solved

**Comment by mdedetrich** [comment]
@gwak So I am diving into this now and I think that I fixed this issue in https://github.com/apache/pekko/pull/1207 so things should be working as expected.

Reading your code example at surface level, maybe the problem is that you are not doing the equivalent of `.lift` which an be seen here https://github.com/apache/pekko/blob/689e30bbe97ba28080130df092372e529e941799/stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowSplitAfterSpec.scala#L219  , you can see the definition of lift [here](https://github.com/apache/pekko/blob/689e30bbe97ba28080130df092372e529e941799/stream-tests/src/test/scala/org/apache/pekko/stream/scaladsl/FlowSplitAfterSpec.scala#L35)

**Comment by gwak** [comment]
@mdedetrich You were right, @pjfanning tried your suggestion in https://github.com/playframework/playframework/pull/12794 and tests are passing. Thanks!

So the final flow is something like :

```scala
...
.splitWhen(_.isLeft)
.prefixAndTail(1)
.map { /*...snip...*/ }
.concatSubstreams
.withAttributes(ActorAttributes.supervisionStrategy(Supervision.resumingDecider))
```

And not 

```scala
...
.splitWhen(_.isLeft)
.withAttributes(ActorAttributes.supervisionStrategy(Supervision.resumingDecider))
.prefixAndTail(1)
.map { /*...snip...*/ }
.concatSubstreams
```

**Comment by mdedetrich** [comment]
Perfect! Closing ticket

**Comment by pjfanning** [comment]
@mdedetrich would you have time to review the Pekko 1.1 migration docs? Would it make sense to suggest that the SupervisionStrategy should be be defined after the concatSubstreams call (if any)?

https://pekko.apache.org/docs/pekko/1.1/migration/migration-guide-1.0.x-1.1.x.html

```
.splitWhen(_.isLeft)
.prefixAndTail(1)
.map { /*...snip...*/ }
.concatSubstreams
.withAttributes(ActorAttributes.supervisionStrategy(Supervision.resumingDecider))
```

**Comment by mdedetrich** [comment]
Sure, I'll do this today

**Comment by mdedetrich** [comment]
PR created at https://github.com/apache/pekko/pull/1391
