### ISSUE TITLE
stream-testkit tests fail with Scala 2.12 - release blocker

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko#1217]
https://github.com/apache/pekko/actions/runs/8397881424/job/23001933349

Started failing about 2 days ago - possibly caused with a day or 2 of March 20.

**Comment by pjfanning** [comment]
@He-Pin you made recent changes to stream-testkit - it's possible that they are causing issues when run with Scala 2.12.

**Comment by He-Pin** [comment]
Let't me check it.
