### ISSUE TITLE
Genjavadoc plugin doesn't support scala 3.3.x

### ISSUE THREAD

**Issue by He-Pin** [apache/pekko#1221]
Should skip the doc in CI for now.

[error] (actor / update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.genjavadoc:genjavadoc-plugin_3.3.3:0.19
[error]   Not found
[error]   Not found
[error]   not found: /home/runner/.ivy2/localcom.typesafe.genjavadoc/genjavadoc-plugin_3.3.3/0.19/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_3.3.3/0.19/genjavadoc-plugin_3.3.3-0.19.pom
[error] (protobuf-v3 / update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.genjavadoc:genjavadoc-plugin_3.3.3:0.19
[error]   Not found
[error]   Not found
[error]   not found: /home/runner/.ivy2/localcom.typesafe.genjavadoc/genjavadoc-plugin_3.3.3/0.19/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_3.3.3/0.19/genjavadoc-plugin_3.3.3-0.19.pom
[error] Total time: 6 s, completed Mar 23, 2024, 6:11:01 PM

**Comment by pjfanning** [comment]
Looks like that plugin has never supported scala 3.

https://mvnrepository.com/artifact/com.typesafe.genjavadoc/genjavadoc-plugin

**Comment by He-Pin** [comment]
> Looks like that plugin has never supported scala 3.
> 
> https://mvnrepository.com/artifact/com.typesafe.genjavadoc/genjavadoc-plugin

Yes, I think that plugin may need be  rewritten with Tasty query? I think we can skip it on 3.3., for now.

**Comment by pjfanning** [comment]
I would prefer if https://github.com/apache/pekko/pull/1226 was done differently. Instead of nor running the `sbt doc` build with Scala 3.3, we could run it but set genjavadoc to false for just that version of Scala.

**Comment by mdedetrich** [comment]
> I would prefer if #1226 was done differently. Instead of nor running the `sbt doc` build with Scala 3.3, we could run it but set genjavadoc to false for just that version of Scala.

Agreed

**Comment by pjfanning** [comment]
this seems fixed
