### ISSUE TITLE
Scala Steward is failing due to heap space issue

### ISSUE THREAD

**Issue by mdedetrich** [apache/pekko#1253]
See https://github.com/scala-steward-org/scala-steward-action/issues/591 for upstream issue

**Comment by mdedetrich** [comment]
Re-opening because its still failing, @He-Pin see https://github.com/apache/pekko/actions/runs/8579695494/job/23514953375

**Comment by He-Pin** [comment]
should we use `./` ?

**Comment by mdedetrich** [comment]
I have no idea, but it does appear the context directory is different.

**Comment by He-Pin** [comment]
maybe I can add a pwd before that

**Comment by mdedetrich** [comment]
> maybe I can add a pwd before that

Create a PR, I'll approve

**Comment by mdedetrich** [comment]
> maybe I can add a pwd before that

Actually I think you can just directly pass the args into the github action, let me have a look

**Comment by pjfanning** [comment]
I think this is fixed
