### ISSUE TITLE
add scala predicate support for retries

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko#1289]
Scala function support for https://github.com/apache/pekko/pull/1269 as well as the Java functions supported in 1269 (BiPredicate).

@kerr is this issue valid? I'm not saying this is urgent, I am just raising it for awareness.

**Comment by He-Pin** [comment]
I think it's currently supported,  does I miss anything ?

**Comment by pjfanning** [comment]
ok - I can see that some code in 1269 uses Scala Functions (`shouldRetry: (Something, Throwable) => throwable`)

**Comment by He-Pin** [comment]
I think this should be more useful, because we have something like Result[T] as rpc result at work.
