### ISSUE TITLE
double "a" appearing in tutorial

### ISSUE THREAD

**Issue by xelbes** [apache/pekko#1357]
hello, 

i am currently working through your tutorial and it appeared that in your tutorial once there is a double "a" because in your java example and in your scala example you added an "a" 

<img width="719" alt="image" src="https://github.com/apache/pekko/assets/88331038/2d88881a-9d45-40b9-93df-d6a1c21a6485">

**Comment by xelbes** [comment]
to explain further 

in the two selection in your markdown you have always added a new "a" 

<img width="909" alt="image" src="https://github.com/apache/pekko/assets/88331038/f680d026-3c9d-4cfb-b555-0c1968b2d150">

**Comment by pjfanning** [comment]
thanks - I created #1358
