### ISSUE TITLE
long running tests should be run in a nightly build

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko#1400]
see #1399 and #1385 (eg SupervisorHierarchySpec)

We have https://github.com/apache/pekko/actions/workflows/timing-tests.yml but that CI job is passing even while 1399 is broken.

**Comment by Roiocam** [comment]
looks like it has been run in night build.

**Comment by pjfanning** [comment]
Thanks @Roiocam 

The test failures can be seen here - https://github.com/apache/pekko/actions/runs/9983318008/job/27590691425
