### ISSUE TITLE
jdk9 tests do not run

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko#1433]
See https://github.com/apache/pekko/pull/1432 - I deliberately modified 2 classes (1 Java, 1 Scala) to see if they were even compiled. The PR did fail because scalafmt and the doc build failed but the main part of the build where we compile code and run tests - this all ran ok.

**Comment by Roiocam** [comment]
I guess `sbt dependWalkerCheck` didn't want to verify JDK9+ classes compile, but I don't remember why it was on purpose.

**Comment by pjfanning** [comment]
#1434 merged
