### ISSUE TITLE
Configuring persistence plugins at runtime for `EventSourcedBehavior`

### ISSUE THREAD

**Issue by ptrdom** [apache/pekko#1513]
One bit of functionality that is present in Classic persistence but missing in Typed is the [capability to configure persistence plugins at runtime](https://doc.akka.io/docs/akka/current/persistence.html#give-persistence-plugin-configurations-at-runtime). Typical case where this is beneficial is for segregation of data between different tenants in multi-tenant environments.

This should be rather straightforward to implement, I could work on it if such feature would be accepted.

**Comment by pjfanning** [comment]
There are API methods in EventSourcedBehavior.

Example:
https://github.com/apache/pekko/blob/main/persistence-typed/src/main/scala/org/apache/pekko/persistence/typed/scaladsl/EventSourcedBehavior.scala#L163

**Comment by ptrdom** [comment]
Providing plugin ID at runtime is not the same as dynamic configuration of the plugin, AFAIK.

**Comment by pjfanning** [comment]
I don't have a problem with having a similar RuntimePluginConfig functionality for EventSourcedBehavior.
@ptrdom Would you be interested in doing a PR for this?

**Comment by ptrdom** [comment]
Yes, will do!
