### ISSUE TITLE
Implement `EventsByTagQuery` in `PersistenceTestKitReadJournal`

### ISSUE THREAD

**Issue by ptrdom** [apache/pekko#1527]
When attempting to implement runtime persistence plugin configuration for pekko-projection I ran into an issue where `PersistenceTestKitReadJournal` does not implement `EventsByTagQuery`, so it cannot be used to implement tests. Real persistence layers,  like Cassandra, JDBC and Leveldb of course do implement `EventsByTagQuery`, but it would be quite useful if testkit was able to provide this behavior too. From a quick look it looks to me like an implementation similar to [EventsByPersistenceIdStage](https://github.com/apache/pekko/blob/95e8355c4c6f2041587e4d64590764e008d1f2b2/persistence-testkit/src/main/scala/org/apache/pekko/persistence/testkit/query/internal/EventsByPersistenceIdStage.scala) should not be too complicated to do.

This is related to https://github.com/apache/pekko/issues/1513 - need to have both `EventSourcedBehavior` and `EventSourcedProvider` be able to take configs at runtime to enable building typical applications using this functionality.

I could work on this feature if it were to be accepted.

**Comment by pjfanning** [comment]
Seems useful to me.
