### ISSUE TITLE
limit spin loop in TLSActor

### ISSUE THREAD

**Issue by He-Pin** [apache/pekko#1633]
Motivation:
There is an Akka 2.6.21 release, which ships this fix with https://github.com/akka/akka/pull/31975

As the release is targeting 2.6.21 which keeps the Apache 2.0 License, will it be safe to port that?

**Comment by pjfanning** [comment]
anything in the 2.6 branch is ok to cherry pick to Pekko

**Comment by He-Pin** [comment]
Close it now, after checking the code, it's been fixed by @pjfanning
