### ISSUE TITLE
Consider publishing changelog in a RenovateBot (and others) compatible way

### ISSUE THREAD

**Issue by gaeljw** [apache/pekko#833]
I'm using RenovateBot to update my dependencies automatically. When suggesting an update, it includes the changelog if found.

Unfortunately, for Pekko dependencies, it's not able to pull the changelog because the changelog is not published in a place Renovate expects to find it.

It would be nice if the changelog could be publisher somewhere Renovate (and other similar tools like dependabot, Scala Steward?) could pull it.

AFAIK Renovate supports at least the following:
- a file `CHANGELOG.md` in the Git repo (assuming the repo URL is published in the POM)
- or, a file `RELEASE-NOTES.md` in the Git repo
- or Github Releases

The 3rd option with Github Releases is maybe something that could be relatively easily be automated?

**Comment by pjfanning** [comment]
The release notes are here: https://pekko.apache.org/docs/pekko/current/release-notes/index.html

For other Pekko modules, it is best to navigate via https://pekko.apache.org/modules.html

In theory, we could add a CHANGELOG.md to each repo that just provides a link to where that repo's related release notes page exists on https://pekko.apache.org

The ASF prefers that our documentation is hosted on apache.org and not dependent on GitHub.

**Comment by gaeljw** [comment]
Makes sense to host the changelog on apache.org as source of truth. But maybe it could be cross-posted to GitHub releases? As you suggest, I think a link to Pekko website from GitHub releases could be enough I guess.

Anyway thanks for the links, I know where to find the release notes now :)
