### ISSUE TITLE
release notes for 1.1.0(-M1)

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko#945]
A list of all the PRs is not that helpful since a lot are doc or build related. Changes backported to 1.0.1 and 1.0.2 should not be included either.

We need a curated list of changes. Ideally. not just highlights but if there are 2 or more PRs that cover the same enhancement, we should list the enhancement once (but maybe link to most or all of the PRs).

**Comment by He-Pin** [comment]
I'm not an English speaker , so ;)

**Comment by pjfanning** [comment]
https://github.com/apache/incubator-pekko/compare/v1.1.0-M0...HEAD
