### ISSUE TITLE
Feature request:Add missing java api for `StreamTestKit`

### ISSUE THREAD

**Issue by He-Pin** [apache/pekko#970]
Motivation:
Currently there are some methods are missing in the StreamTestkit for javadsl. And which is very annoying when you implement  a `GraphStage` in Java and test it in pure Java.

I think this task is easy if anyone else in the community want to take a try. otherwise I would like to prepare this this weekend, because I coding in java everyday.

Result:
More friendly for Java end users.

**Comment by He-Pin** [comment]
@naosense Thanks for intreast this.

![Screenshot_20240118_180539_GitHub.jpg](https://github.com/apache/incubator-pekko/assets/501740/3ef3df39-c829-48af-9b2a-481022e510bc)

This one, you will see there are many scala methods don't have related java api.

**Comment by naosense** [comment]
As it was said in the WeChat group, should I change FiniteDuration to java.time.Duration, or add some equalent methods with java.time.Duration?

**Comment by mdedetrich** [comment]
> As it was said in the WeChat group, should I change FiniteDuration to java.time.Duration, or add some equalent methods with java.time.Duration?

@naosense Yes you should, other parts of the `javaapi` for pekko-streams use `java.time.Duration`

**Comment by He-Pin** [comment]
I was on meeting, you should keep the method the same, but adopt the Scala type to Java native type.

**Comment by He-Pin** [comment]
@naosense You can take a look at https://github.com/apache/incubator-pekko/blob/main/CONTRIBUTING.md#java-apis-in-pekko for the type mapping, hope you have a nice ride, and thank you.

**Comment by naosense** [comment]
I created a PR, but I don't have permission to add a reviewer, please take a look when you have time @He-Pin

**Comment by mdedetrich** [comment]
> I created a PR, but I don't have permission to add a reviewer, please take a look when you have time @He-Pin

Done
