### ISSUE TITLE
[DOC] Style Guide document render issue

### ISSUE THREAD

**Issue by Roiocam** [apache/pekko#975]
On Index page: https://pekko.apache.org/docs/pekko/current/typed/index.html

style guide TOC not correctly rendering.

<img width="429" alt="截屏2024-01-18 00 11 10" src="https://github.com/apache/incubator-pekko/assets/26020358/b070e4b8-9e3d-4f6b-8ad8-91dc4d238f84">

## short investigation

Style Guide Page TOC has diffrence content on diffrence Programming language, but it may be due to the incorrect use of Paradox Or Paradox issue, Need to figure it out.

<img width="1441" alt="截屏2024-01-18 00 11 40" src="https://github.com/apache/incubator-pekko/assets/26020358/93d6deaa-707f-48b3-9a4f-621d027a92d6">

<img width="1412" alt="截屏2024-01-18 00 11 48" src="https://github.com/apache/incubator-pekko/assets/26020358/6af650eb-d006-4569-a969-c0eae2450d4c">

**Comment by Roiocam** [comment]
after git blame investigation, i believe this is the issue of paradox.

**Comment by He-Pin** [comment]
![Screenshot_20240118_003001_Samsung Internet.jpg](https://github.com/apache/incubator-pekko/assets/501740/906aeca7-fa6e-49c6-b446-e0d9fbf61a6e)

Thanks, just checked and yes, maybe some kind of issue issue ？

**Comment by samueleresca** [comment]
I think because paradox tries to hide from the list the sections that are Java or Scala only if you change the selected language

**Comment by Roiocam** [comment]
> I think because paradox tries to hide from the list the sections that are Java or Scala only if you change the selected language

I think that the "index" page rendering does not filter out the Children in a particular language from the list.

 And I think is an achievable considering that paradox will add class of "group xxx" to these Children DOM.

**Comment by Roiocam** [comment]
closed via [#72](https://github.com/apache/pekko-site/pull/72)
